require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native/scripts/react_native_pods'

platform :ios, '13.4'

target 'MLApp' do
  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => true,
  )

  post_install do |installer|
    react_native_post_install(installer)
  end
end
